version: "3.9"

x-router-common: &router-common
  image: frrouting/frr:latest
  privileged: true
  cap_add:
    - NET_ADMIN
  volumes:
    - ./:/opt/ospf-gaming
  command: >-
    /bin/sh -c "sysctl -w net.ipv4.ip_forward=1 && /usr/lib/frr/frrinit.sh start && tail -f /dev/null"

services:
  r1:
    <<: *router-common
    hostname: r1
    container_name: r1
    networks:
      net_r1_r2:
        ipv4_address: 10.0.12.1
      net_r1_r3:
        ipv4_address: 10.0.13.1
      net_r1_h1:
        ipv4_address: 10.0.101.1

  r2:
    <<: *router-common
    hostname: r2
    container_name: r2
    networks:
      net_r1_r2:
        ipv4_address: 10.0.12.2
      net_r2_r3:
        ipv4_address: 10.0.23.1
      net_r2_r4:
        ipv4_address: 10.0.24.1

  r3:
    <<: *router-common
    hostname: r3
    container_name: r3
    networks:
      net_r1_r3:
        ipv4_address: 10.0.13.2
      net_r2_r3:
        ipv4_address: 10.0.23.2
      net_r3_r5:
        ipv4_address: 10.0.35.1

  r4:
    <<: *router-common
    hostname: r4
    container_name: r4
    networks:
      net_r2_r4:
        ipv4_address: 10.0.24.2
      net_r4_r5:
        ipv4_address: 10.0.45.1
      net_r4_r6:
        ipv4_address: 10.0.46.1

  r5:
    <<: *router-common
    hostname: r5
    container_name: r5
    networks:
      net_r3_r5:
        ipv4_address: 10.0.35.2
      net_r4_r5:
        ipv4_address: 10.0.45.2
      net_r5_r7:
        ipv4_address: 10.0.57.1

  r6:
    <<: *router-common
    hostname: r6
    container_name: r6
    networks:
      net_r4_r6:
        ipv4_address: 10.0.46.2
      net_r6_r7:
        ipv4_address: 10.0.67.1
      net_r6_r8:
        ipv4_address: 10.0.68.1

  r7:
    <<: *router-common
    hostname: r7
    container_name: r7
    networks:
      net_r5_r7:
        ipv4_address: 10.0.57.2
      net_r6_r7:
        ipv4_address: 10.0.67.2
      net_r7_r8:
        ipv4_address: 10.0.78.1

  r8:
    <<: *router-common
    hostname: r8
    container_name: r8
    networks:
      net_r6_r8:
        ipv4_address: 10.0.68.2
      net_r7_r8:
        ipv4_address: 10.0.78.2
      net_r8_h2:
        ipv4_address: 10.0.108.1

  h1:
    image: alpine:3.19
    hostname: h1
    container_name: h1
    command: sh -c "tail -f /dev/null"
    networks:
      net_r1_h1:
        ipv4_address: 10.0.101.2

  h2:
    image: alpine:3.19
    hostname: h2
    container_name: h2
    command: sh -c "tail -f /dev/null"
    networks:
      net_r8_h2:
        ipv4_address: 10.0.108.2

networks:
  net_r1_r2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.12.0/30

  net_r1_r3:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.13.0/30

  net_r2_r3:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.23.0/30

  net_r2_r4:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.24.0/30

  net_r3_r5:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.35.0/30

  net_r4_r5:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.45.0/30

  net_r4_r6:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.46.0/30

  net_r5_r7:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.57.0/30

  net_r6_r7:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.67.0/30

  net_r6_r8:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.68.0/30

  net_r7_r8:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.78.0/30

  net_r1_h1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.101.0/30

  net_r8_h2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.108.0/30
