services:
  # Roteadores
  r1:
    build: .
    container_name: r1
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true 
    networks:
      net-r1-r2:
        ipv4_address: 10.1.2.10
      net-r1-r3:
        ipv4_address: 10.1.3.10 
    tty: true
    environment:
      - ROUTER_ID=1.1.1.1

  r2:
    build: .
    container_name: r2
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true
    networks:
      net-r1-r2:
        ipv4_address: 10.1.2.20 
      net-r2-r4:
        ipv4_address: 10.2.4.20 
      net-r2-r5:
        ipv4_address: 10.2.5.20 
    tty: true
    environment:
      - ROUTER_ID=2.2.2.2

  r3:
    build: .
    container_name: r3
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true
    networks:
      net-r1-r3:
        ipv4_address: 10.1.3.30 
      net-r3-r4:
        ipv4_address: 10.3.4.30 
      net-r3-r6:
        ipv4_address: 10.3.6.30 
    tty: true
    environment:
      - ROUTER_ID=3.3.3.3

  r4:
    build: .
    container_name: r4
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true
    networks:
      net-r2-r4:
        ipv4_address: 10.2.4.40 
      net-r3-r4:
        ipv4_address: 10.3.4.40 
      net-r4-r7:
        ipv4_address: 10.4.7.40 
    tty: true
    environment:
      - ROUTER_ID=4.4.4.4

  r5:
    build: .
    container_name: r5
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true
    networks:
      net-r2-r5:
        ipv4_address: 10.2.5.50 
      net-h1-r5:
        ipv4_address: 10.10.1.50 
    tty: true
    environment:
      - ROUTER_ID=5.5.5.5

  r6:
    build: .
    container_name: r6
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true
    networks:
      net-r3-r6:
        ipv4_address: 10.3.6.60 
      net-r6-r8:
        ipv4_address: 10.6.8.60 
    tty: true
    environment:
      - ROUTER_ID=6.6.6.6

  r7:
    build: .
    container_name: r7
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true
    networks:
      net-r4-r7:
        ipv4_address: 10.4.7.70 
      net-r7-r8:
        ipv4_address: 10.7.8.70 
    tty: true
    environment:
      - ROUTER_ID=7.7.7.7

  r8:
    build: .
    container_name: r8
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true
    networks:
      net-r6-r8:
        ipv4_address: 10.6.8.80
      net-r7-r8:
        ipv4_address: 10.7.8.80 
      net-h2-r8:
        ipv4_address: 10.10.2.80 
    tty: true
    environment:
      - ROUTER_ID=8.8.8.8

  h1:
    build:
      context: .
      dockerfile: Dockerfile.host
    container_name: h1
    cap_add:
      - NET_ADMIN
    command: >
      bash -c "ip route replace default via 10.10.1.50 && tail -f /dev/null" 
    networks:
      net-h1-r5:
        ipv4_address: 10.10.1.100

  h2:
    build:
      context: .
      dockerfile: Dockerfile.host
    container_name: h2
    cap_add:
      - NET_ADMIN
    command: >
      bash -c "ip route replace default via 10.10.2.80 && tail -f /dev/null" 
    networks:
      net-h2-r8:
        ipv4_address: 10.10.2.100

networks:
  net-r1-r2:
    ipam:
      config:
        - subnet: 10.1.2.0/24
  net-r1-r3:
    ipam:
      config:
        - subnet: 10.1.3.0/24
  net-r2-r4:
    ipam:
      config:
        - subnet: 10.2.4.0/24
  net-r2-r5:
    ipam:
      config:
        - subnet: 10.2.5.0/24
  net-r3-r4:
    ipam:
      config:
        - subnet: 10.3.4.0/24
  net-r3-r6:
    ipam:
      config:
        - subnet: 10.3.6.0/24
  net-r4-r7:
    ipam:
      config:
        - subnet: 10.4.7.0/24
  net-r6-r8:
    ipam:
      config:
        - subnet: 10.6.8.0/24
  net-r7-r8:
    ipam:
      config:
        - subnet: 10.7.8.0/24
  net-h1-r5:
    ipam:
      config:
        - subnet: 10.10.1.0/24
  net-h2-r8:
    ipam:
      config:
        - subnet: 10.10.2.0/24